// Generated by gencpp from file rover_msgs/roverGoalStatus.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ROVERGOALSTATUS_H
#define ROVER_MSGS_MESSAGE_ROVERGOALSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct roverGoalStatus_
{
  typedef roverGoalStatus_<ContainerAllocator> Type;

  roverGoalStatus_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)
    , status(0)
    , goal_id(0)
    , text()  {
    }
  roverGoalStatus_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)
    , status(0)
    , goal_id(0)
    , text(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _orientation_x_type;
  _orientation_x_type orientation_x;

   typedef double _orientation_y_type;
  _orientation_y_type orientation_y;

   typedef double _orientation_z_type;
  _orientation_z_type orientation_z;

   typedef double _orientation_w_type;
  _orientation_w_type orientation_w;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _goal_id_type;
  _goal_id_type goal_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(PENDING)
  #undef PENDING
#endif
#if defined(_WIN32) && defined(ACTIVE)
  #undef ACTIVE
#endif
#if defined(_WIN32) && defined(PREEMPTED)
  #undef PREEMPTED
#endif
#if defined(_WIN32) && defined(SUCCEEDED)
  #undef SUCCEEDED
#endif
#if defined(_WIN32) && defined(ABORTED)
  #undef ABORTED
#endif
#if defined(_WIN32) && defined(REJECTED)
  #undef REJECTED
#endif
#if defined(_WIN32) && defined(PREEMPTING)
  #undef PREEMPTING
#endif
#if defined(_WIN32) && defined(RECALLING)
  #undef RECALLING
#endif
#if defined(_WIN32) && defined(RECALLED)
  #undef RECALLED
#endif
#if defined(_WIN32) && defined(LOST)
  #undef LOST
#endif

  enum {
    PENDING = 0u,
    ACTIVE = 1u,
    PREEMPTED = 2u,
    SUCCEEDED = 3u,
    ABORTED = 4u,
    REJECTED = 5u,
    PREEMPTING = 6u,
    RECALLING = 7u,
    RECALLED = 8u,
    LOST = 9u,
  };


  typedef boost::shared_ptr< ::rover_msgs::roverGoalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::roverGoalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct roverGoalStatus_

typedef ::rover_msgs::roverGoalStatus_<std::allocator<void> > roverGoalStatus;

typedef boost::shared_ptr< ::rover_msgs::roverGoalStatus > roverGoalStatusPtr;
typedef boost::shared_ptr< ::rover_msgs::roverGoalStatus const> roverGoalStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::roverGoalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover_msgs::roverGoalStatus_<ContainerAllocator1> & lhs, const ::rover_msgs::roverGoalStatus_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.orientation_x == rhs.orientation_x &&
    lhs.orientation_y == rhs.orientation_y &&
    lhs.orientation_z == rhs.orientation_z &&
    lhs.orientation_w == rhs.orientation_w &&
    lhs.status == rhs.status &&
    lhs.goal_id == rhs.goal_id &&
    lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover_msgs::roverGoalStatus_<ContainerAllocator1> & lhs, const ::rover_msgs::roverGoalStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::roverGoalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::roverGoalStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::roverGoalStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06fdaffd0dd12907d78dce66dec8b35a";
  }

  static const char* value(const ::rover_msgs::roverGoalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06fdaffd0dd12907ULL;
  static const uint64_t static_value2 = 0xd78dce66dec8b35aULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/roverGoalStatus";
  }

  static const char* value(const ::rover_msgs::roverGoalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 PENDING=0\n"
"uint8 ACTIVE=1\n"
"uint8 PREEMPTED=2\n"
"uint8 SUCCEEDED=3\n"
"uint8 ABORTED=4\n"
"uint8 REJECTED=5\n"
"uint8 PREEMPTING=6\n"
"uint8 RECALLING=7\n"
"uint8 RECALLED=8\n"
"uint8 LOST=9\n"
"\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 orientation_x\n"
"float64 orientation_y\n"
"float64 orientation_z\n"
"float64 orientation_w\n"
"uint8 status\n"
"uint8 goal_id\n"
"string text\n"
;
  }

  static const char* value(const ::rover_msgs::roverGoalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.orientation_x);
      stream.next(m.orientation_y);
      stream.next(m.orientation_z);
      stream.next(m.orientation_w);
      stream.next(m.status);
      stream.next(m.goal_id);
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct roverGoalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::roverGoalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::roverGoalStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation_x: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation_y: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation_z: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation_w: ";
    Printer<double>::stream(s, indent + "  ", v.orientation_w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ROVERGOALSTATUS_H
