// Generated by gencpp from file rover_msgs/roverBmsStatus.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ROVERBMSSTATUS_H
#define ROVER_MSGS_MESSAGE_ROVERBMSSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rover_msgs
{
template <class ContainerAllocator>
struct roverBmsStatus_
{
  typedef roverBmsStatus_<ContainerAllocator> Type;

  roverBmsStatus_()
    : header()
    , percentage(0)
    , voltage(0.0)
    , current(0.0)
    , temperature(0.0)  {
    }
  roverBmsStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , percentage(0)
    , voltage(0.0)
    , current(0.0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _percentage_type;
  _percentage_type percentage;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef double _current_type;
  _current_type current;

   typedef double _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::rover_msgs::roverBmsStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::roverBmsStatus_<ContainerAllocator> const> ConstPtr;

}; // struct roverBmsStatus_

typedef ::rover_msgs::roverBmsStatus_<std::allocator<void> > roverBmsStatus;

typedef boost::shared_ptr< ::rover_msgs::roverBmsStatus > roverBmsStatusPtr;
typedef boost::shared_ptr< ::rover_msgs::roverBmsStatus const> roverBmsStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::roverBmsStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover_msgs::roverBmsStatus_<ContainerAllocator1> & lhs, const ::rover_msgs::roverBmsStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.percentage == rhs.percentage &&
    lhs.voltage == rhs.voltage &&
    lhs.current == rhs.current &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover_msgs::roverBmsStatus_<ContainerAllocator1> & lhs, const ::rover_msgs::roverBmsStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::roverBmsStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::roverBmsStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::roverBmsStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e98861cb0e01a28a1d9239e1cc17878";
  }

  static const char* value(const ::rover_msgs::roverBmsStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e98861cb0e01a28ULL;
  static const uint64_t static_value2 = 0xa1d9239e1cc17878ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/roverBmsStatus";
  }

  static const char* value(const ::rover_msgs::roverBmsStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"char percentage\n"
"float64 voltage\n"
"float64 current\n"
"float64 temperature\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rover_msgs::roverBmsStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.percentage);
      stream.next(m.voltage);
      stream.next(m.current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct roverBmsStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::roverBmsStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::roverBmsStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "percentage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.percentage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ROVERBMSSTATUS_H
