(cl:defpackage rover_msgs-msg
  (:use )
  (:export
   "<ROVERBMSSTATUS>"
   "ROVERBMSSTATUS"
   "<ROVERGOALSTATUS>"
   "ROVERGOALSTATUS"
   "<ROVERRCSTATUS>"
   "ROVERRCSTATUS"
   "<ROVERBMSSTATUS>"
   "ROVERBMSSTATUS"
   "<ROVERGOALSTATUS>"
   "ROVERGOALSTATUS"
   "<ROVERRCSTATUS>"
   "ROVERRCSTATUS"
  ))

