# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_msgs/roverGoalStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class roverGoalStatus(genpy.Message):
  _md5sum = "06fdaffd0dd12907d78dce66dec8b35a"
  _type = "rover_msgs/roverGoalStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 PENDING=0
uint8 ACTIVE=1
uint8 PREEMPTED=2
uint8 SUCCEEDED=3
uint8 ABORTED=4
uint8 REJECTED=5
uint8 PREEMPTING=6
uint8 RECALLING=7
uint8 RECALLED=8
uint8 LOST=9


float64 x
float64 y
float64 z
float64 orientation_x
float64 orientation_y
float64 orientation_z
float64 orientation_w
uint8 status
uint8 goal_id
string text"""
  # Pseudo-constants
  PENDING = 0
  ACTIVE = 1
  PREEMPTED = 2
  SUCCEEDED = 3
  ABORTED = 4
  REJECTED = 5
  PREEMPTING = 6
  RECALLING = 7
  RECALLED = 8
  LOST = 9

  __slots__ = ['x','y','z','orientation_x','orientation_y','orientation_z','orientation_w','status','goal_id','text']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','uint8','uint8','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,orientation_x,orientation_y,orientation_z,orientation_w,status,goal_id,text

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(roverGoalStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.orientation_x is None:
        self.orientation_x = 0.
      if self.orientation_y is None:
        self.orientation_y = 0.
      if self.orientation_z is None:
        self.orientation_z = 0.
      if self.orientation_w is None:
        self.orientation_w = 0.
      if self.status is None:
        self.status = 0
      if self.goal_id is None:
        self.goal_id = 0
      if self.text is None:
        self.text = ''
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.orientation_x = 0.
      self.orientation_y = 0.
      self.orientation_z = 0.
      self.orientation_w = 0.
      self.status = 0
      self.goal_id = 0
      self.text = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d2B().pack(_x.x, _x.y, _x.z, _x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.status, _x.goal_id))
      _x = self.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 58
      (_x.x, _x.y, _x.z, _x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.status, _x.goal_id,) = _get_struct_7d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d2B().pack(_x.x, _x.y, _x.z, _x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.status, _x.goal_id))
      _x = self.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 58
      (_x.x, _x.y, _x.z, _x.orientation_x, _x.orientation_y, _x.orientation_z, _x.orientation_w, _x.status, _x.goal_id,) = _get_struct_7d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d2B = None
def _get_struct_7d2B():
    global _struct_7d2B
    if _struct_7d2B is None:
        _struct_7d2B = struct.Struct("<7d2B")
    return _struct_7d2B
