# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_msgs/roverRCStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class roverRCStatus(genpy.Message):
  _md5sum = "c06b6cb58b0a81562a8993101c944318"
  _type = "rover_msgs/roverRCStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

bool connect
int8 CH1
int8 CH2
int8 CH3
int8 CH4
int8 CH5
int8 CH6
int8 CH7
int8 CH8
int8 CH9
int8 CH10
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','connect','CH1','CH2','CH3','CH4','CH5','CH6','CH7','CH8','CH9','CH10']
  _slot_types = ['std_msgs/Header','bool','int8','int8','int8','int8','int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,connect,CH1,CH2,CH3,CH4,CH5,CH6,CH7,CH8,CH9,CH10

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(roverRCStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.connect is None:
        self.connect = False
      if self.CH1 is None:
        self.CH1 = 0
      if self.CH2 is None:
        self.CH2 = 0
      if self.CH3 is None:
        self.CH3 = 0
      if self.CH4 is None:
        self.CH4 = 0
      if self.CH5 is None:
        self.CH5 = 0
      if self.CH6 is None:
        self.CH6 = 0
      if self.CH7 is None:
        self.CH7 = 0
      if self.CH8 is None:
        self.CH8 = 0
      if self.CH9 is None:
        self.CH9 = 0
      if self.CH10 is None:
        self.CH10 = 0
    else:
      self.header = std_msgs.msg.Header()
      self.connect = False
      self.CH1 = 0
      self.CH2 = 0
      self.CH3 = 0
      self.CH4 = 0
      self.CH5 = 0
      self.CH6 = 0
      self.CH7 = 0
      self.CH8 = 0
      self.CH9 = 0
      self.CH10 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B10b().pack(_x.connect, _x.CH1, _x.CH2, _x.CH3, _x.CH4, _x.CH5, _x.CH6, _x.CH7, _x.CH8, _x.CH9, _x.CH10))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.connect, _x.CH1, _x.CH2, _x.CH3, _x.CH4, _x.CH5, _x.CH6, _x.CH7, _x.CH8, _x.CH9, _x.CH10,) = _get_struct_B10b().unpack(str[start:end])
      self.connect = bool(self.connect)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B10b().pack(_x.connect, _x.CH1, _x.CH2, _x.CH3, _x.CH4, _x.CH5, _x.CH6, _x.CH7, _x.CH8, _x.CH9, _x.CH10))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.connect, _x.CH1, _x.CH2, _x.CH3, _x.CH4, _x.CH5, _x.CH6, _x.CH7, _x.CH8, _x.CH9, _x.CH10,) = _get_struct_B10b().unpack(str[start:end])
      self.connect = bool(self.connect)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B10b = None
def _get_struct_B10b():
    global _struct_B10b
    if _struct_B10b is None:
        _struct_B10b = struct.Struct("<B10b")
    return _struct_B10b
